[project]
name = "cs229"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "einops>=0.8.1",
    "numpy>=1.24.4",
    "pyreadstat>=1.3.0",
    "torch>=2.5.1",
]
